namespace: prod
# replica_count: 4
hpa:
  min_replicas: 2
  max_replicas: 10
  target_cpu_util: 50
network:
  external_port: 30200
configmap:
  data:
    KEY1: 'PROD1'
image:
  tag: v1.0.0
security: true