kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  KEY1: {{ .Values.configmap.data.KEY1 }}
  KEY2: {{ .Values.configmap.data.KEY2 }}
  KEY3: {{ .Values.configmap.data.KEY3 }}