
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app_name }}
spec:
  ports:
  - port: {{ .Values.network.port }}
    targetPort: {{ .Values.network.port }}
    nodePort: {{ .Values.network.external_port }}
  selector:
    app: {{ .Values.app_name }}
  type: NodePort